
INSERT INTO [Raw_Activity]
    ([bk_PlanId], [AssetName], [ParentName], [Description], [NetRate], [Percentage], [StartYear], [ActivityCycle], [EndYear], [FrequencyInYear], [Quantity], [Contractor], [Unplanned], [Committed], [ref_ActivityTypeReference], [ref_ElementTypeReference], [ref_UnitOfMeasureReference], [CustomImpact1Rate], [CustomImpact2Rate], [CustomImpact3Rate], [CustomImpact4Rate], [CustomImpact5Rate], [SortOrder], [sk_Id], [bk_Id], [bk_TenantId], [target_Date], [source_DateCreated], [source_DateLastModified], [EntityStatus], [Load_DateTime])
SELECT
    Tbl.Col.value('bk_PlanId[1]', 'nvarchar(40)') AS [bk_PlanId],
    Tbl.Col.value('AssetName[1]', 'nvarchar(max)') AS [AssetName],
    Tbl.Col.value('ParentName[1]', 'nvarchar(max)') AS [ParentName],
    Tbl.Col.value('Description[1]', 'nvarchar(max)') AS [Description],
    Tbl.Col.value('NetRate[1]', 'nvarchar(40)') AS [NetRate],
    Tbl.Col.value('Percentage[1]', 'nvarchar(40)') AS [Percentage],
    Tbl.Col.value('StartYear[1]', 'nvarchar(40)') AS [StartYear],
    Tbl.Col.value('ActivityCycle[1]', 'nvarchar(40)') AS [ActivityCycle],
    Tbl.Col.value('EndYear[1]', 'nvarchar(40)') AS [EndYear],
    Tbl.Col.value('FrequencyInYear[1]', 'nvarchar(40)') AS [FrequencyInYear],
    Tbl.Col.value('Quantity[1]', 'nvarchar(40)') AS [Quantity],
    Tbl.Col.value('Contractor[1]', 'nvarchar(max)') AS [Contractor],
    Tbl.Col.value('Unplanned[1]', 'nvarchar(40)') AS [Unplanned],
    Tbl.Col.value('Committed[1]', 'nvarchar(40)') AS [Committed],
    Tbl.Col.value('ref_ActivityTypeReference[1]', 'nvarchar(max)') AS [ref_ActivityTypeReference],
    Tbl.Col.value('ref_ElementTypeReference[1]', 'nvarchar(max)') AS [ref_ElementTypeReference],
    Tbl.Col.value('ref_UnitOfMeasureReference[1]', 'nvarchar(max)') AS [ref_UnitOfMeasureReference],
    Tbl.Col.value('CustomImpact1Rate[1]', 'nvarchar(40)') AS [CustomImpact1Rate],
    Tbl.Col.value('CustomImpact2Rate[1]', 'nvarchar(40)') AS [CustomImpact2Rate],
    Tbl.Col.value('CustomImpact3Rate[1]', 'nvarchar(40)') AS [CustomImpact3Rate],
    Tbl.Col.value('CustomImpact4Rate[1]', 'nvarchar(40)') AS [CustomImpact4Rate],
    Tbl.Col.value('CustomImpact5Rate[1]', 'nvarchar(40)') AS [CustomImpact5Rate],
    Tbl.Col.value('SortOrder[1]', 'nvarchar(40)') AS [SortOrder],
    Tbl.Col.value('sk_Id[1]', 'nvarchar(40)') AS [sk_Id],
    Tbl.Col.value('bk_Id[1]', 'nvarchar(40)') AS [bk_Id],
    Tbl.Col.value('bk_TenantId[1]', 'nvarchar(40)') AS [bk_TenantId],
    Tbl.Col.value('target_Date[1]', 'nvarchar(40)') AS [target_Date],
    Tbl.Col.value('source_DateCreated[1]', 'nvarchar(40)') AS [source_DateCreated],
    Tbl.Col.value('source_DateLastModified[1]', 'nvarchar(40)') AS [source_DateLastModified],
    Tbl.Col.value('EntityStatus[1]', 'nvarchar(max)') AS [EntityStatus],
    sysdatetime() as [Load_DateTime] 
FROM @Entities.nodes('//Entity') Tbl(Col);
