INSERT INTO [raw].[Site]
    ([Name], [Description], [GrossFloorArea], [SiteFootprintArea], [AreaUnit], [MainUsage], [ConstructionCompletionDate], [OperationalStartDate], [LastMajorRefurbishmentDate], [EndOfOperationContractDate], [PeriodOfInterest], [RebuildValue], [Latitude], [Longitude], [PostCode], [Country], [Contract], [ContractEndCondition], [ContractEndResidualLife], [Customer], [ref_SectorReference], [ref_RegionReference], [ref_InsuranceReference], [HoursOfOperation], [BaseDate], [CurrentForecastPlanbk_Id], [CurrentBudgetPlanbk_Id], [Location], [ResidualLifeStartDate], [IdPath], [ExternalUUID], [sk_Id], [bk_Id], [bk_TenantId], [target_Date], [source_DateCreated], [source_DateLastModified], [EntityStatus], [Load_DateTime])
SELECT
    Tbl.Col.value('Name[1]', 'nvarchar(max)') AS [Name],
    Tbl.Col.value('Description[1]', 'nvarchar(max)') AS [Description],
    Tbl.Col.value('GrossFloorArea[1]', 'nvarchar(40)') AS [GrossFloorArea],
    Tbl.Col.value('SiteFootprintArea[1]', 'nvarchar(40)') AS [SiteFootprintArea],
    Tbl.Col.value('AreaUnit[1]', 'nvarchar(max)') AS [AreaUnit],
    Tbl.Col.value('MainUsage[1]', 'nvarchar(max)') AS [MainUsage],
    Tbl.Col.value('ConstructionCompletionDate[1]', 'nvarchar(40)') AS [ConstructionCompletionDate],
    Tbl.Col.value('OperationalStartDate[1]', 'nvarchar(40)') AS [OperationalStartDate],
    Tbl.Col.value('LastMajorRefurbishmentDate[1]', 'nvarchar(40)') AS [LastMajorRefurbishmentDate],
    Tbl.Col.value('EndOfOperationContractDate[1]', 'nvarchar(40)') AS [EndOfOperationContractDate],
    Tbl.Col.value('PeriodOfInterest[1]', 'nvarchar(max)') AS [PeriodOfInterest],
    Tbl.Col.value('RebuildValue[1]', 'nvarchar(40)') AS [RebuildValue],
    Tbl.Col.value('Latitude[1]', 'nvarchar(40)') AS [Latitude],
    Tbl.Col.value('Longitude[1]', 'nvarchar(40)') AS [Longitude],
    Tbl.Col.value('PostCode[1]', 'nvarchar(40)') AS [PostCode],
    Tbl.Col.value('Country[1]', 'nvarchar(max)') AS [Country],
    Tbl.Col.value('Contract[1]', 'nvarchar(max)') AS [Contract],
    Tbl.Col.value('ContractEndCondition[1]', 'nvarchar(max)') AS [ContractEndCondition],
    Tbl.Col.value('ContractEndResidualLife[1]', 'nvarchar(40)') AS [ContractEndResidualLife],
    Tbl.Col.value('Customer[1]', 'nvarchar(max)') AS [Customer],
    Tbl.Col.value('ref_SectorReference[1]', 'nvarchar(max)') AS [ref_SectorReference],
    Tbl.Col.value('ref_RegionReference[1]', 'nvarchar(max)') AS [ref_RegionReference],
    Tbl.Col.value('ref_InsuranceReference[1]', 'nvarchar(max)') AS [ref_InsuranceReference],
    Tbl.Col.value('HoursOfOperation[1]', 'nvarchar(max)') AS [HoursOfOperation],
    Tbl.Col.value('BaseDate[1]', 'nvarchar(40)') AS [BaseDate],
    Tbl.Col.value('CurrentForecastPlanbk_Id[1]', 'nvarchar(40)') AS [CurrentForecastPlanbk_Id],
    Tbl.Col.value('CurrentBudgetPlanbk_Id[1]', 'nvarchar(40)') AS [CurrentBudgetPlanbk_Id],
    Tbl.Col.value('Location[1]', 'nvarchar(max)') AS [Location],
    Tbl.Col.value('ResidualLifeStartDate[1]', 'nvarchar(40)') AS [ResidualLifeStartDate],
    Tbl.Col.value('IdPath[1]', 'nvarchar(max)') AS [IdPath],
    Tbl.Col.value('ExternalUUID[1]', 'nvarchar(40)') AS [ExternalUUID],
    Tbl.Col.value('sk_Id[1]', 'nvarchar(40)') AS [sk_Id],
    Tbl.Col.value('bk_Id[1]', 'nvarchar(40)') AS [bk_Id],
    Tbl.Col.value('bk_TenantId[1]', 'nvarchar(40)') AS [bk_TenantId],
    Tbl.Col.value('target_Date[1]', 'nvarchar(40)') AS [target_Date],
    Tbl.Col.value('source_DateCreated[1]', 'nvarchar(40)') AS [source_DateCreated],
    Tbl.Col.value('source_DateLastModified[1]', 'nvarchar(40)') AS [source_DateLastModified],
    Tbl.Col.value('EntityStatus[1]', 'nvarchar(max)') AS [EntityStatus],
    @RunIdentifier as [Load_DateTime] 
FROM @Entities.nodes('//Entity') Tbl(Col)
LEFT JOIN (SELECT [bk_id] FROM [raw].[Site] WHERE [Load_DateTime] = @RunIdentifier) AS [existing]
ON Tbl.Col.value('bk_Id[1]', 'nvarchar(40)') = [existing].[bk_id]
WHERE [existing].[bk_id] IS NULL;